# Generated by Django 3.1.2 on 2021-09-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_module', '0001_initial'),
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.employee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='employerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_module.employer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paymentId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_module.payment'),
        ),
        migrations.AddField(
            model_name='commission',
            name='agencyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_module.recrutingagency'),
        ),
        migrations.AddField(
            model_name='commission',
            name='paymentId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_module.payment'),
        ),
    ]
