# Generated by Django 3.1.2 on 2021-09-23 21:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0002_auto_20210923_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 139456)),
        ),
        migrations.AddField(
            model_name='commission',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 139456)),
        ),
        migrations.AddField(
            model_name='employer',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
        migrations.AddField(
            model_name='payment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
        migrations.AddField(
            model_name='payment',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 0, 4, 23, 138459)),
        ),
    ]
