# Generated by Django 3.1.2 on 2021-09-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0004_auto_20210924_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='agencyId',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='paymentId',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='employeeId',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='employerId',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='paymentId',
            new_name='payment',
        ),
    ]
