# Generated by Django 3.1.2 on 2021-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0006_auto_20211002_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
