# Generated by Django 3.1.2 on 2021-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0007_auto_20211015_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
