# Generated by Django 3.1.2 on 2021-09-23 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_module', '0004_auto_20210924_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recrutingagency',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supersite',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
