# Generated by Django 3.1.2 on 2021-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_auto_20210924_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recrutingagency',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supersite',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='recrutingagency',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='supersite',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
