# Generated by Django 3.1.2 on 2021-10-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0006_auto_20211002_1644'),
        ('user_module', '0007_auto_20211002_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_module.recrutingagency'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_module.employer'),
        ),
    ]
