# Generated by Django 3.1.2 on 2021-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0009_auto_20211015_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bankAccountNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
